super_sprinter/sprinter/urls.py
from django.urls import path

from . import views

app_name = 'sprinter'

urlpatterns = [
    path('', views.projects_list, name='projects_list'),
    path('project/<int:project_id>/', views.project_detail, name='project_detail'),
    path('add/project/', views.add_project, name='add_project'),
    path('delete/project/<int:project_id>/', views.delete_project, name='delete_project'),
    path('add/story/', views.add_story, name='add_story'),
    path('edit/project/<str:project_title>/', views.edit_project, name='edit_project'),
    path('edit/story/<int:story_id>/', views.edit_story, name='edit_story'),

]

super_sprinter/super_sprinter/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sprinter.urls'))
]

super_sprinter/sprinter/models.py
import datetime

from django.db import models


class Project(models.Model):
    project_title = models.CharField(max_length=30)
    pub_date = models.DateTimeField(default=datetime.datetime.now)

    def __str__(self):
        return self.project_title


class Story(models.Model):
    project = models.ForeignKey(Project,
                                on_delete=models.CASCADE)
    story_title = models.CharField(max_length=30)
    user_story = models.TextField()
    acceptance_criteria = models.TextField()
    business_value = models.PositiveIntegerField(default=0)
    estimation = models.PositiveIntegerField(default=0)

    @property
    def value(self):
        return self.business_value // self.estimation

    class Meta:
        verbose_name = "Story"
        verbose_name_plural = "Stories"

    def __str__(self):
        return self.story_title

super_sprinter/sprinter/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

from .models import Project, Story


def projects_list(request):
    projects_list = Project.objects.all()
    context = {'projects_list': projects_list}
    return render(request, 'sprinter/projects_list.html', context)

def project_detail(request, project_id):
    project = Project.objects.get(id=project_id)
    stories = Story.objects.filter(project = project_id)
    context = {'project': project,
               'stories': stories}
    return render(request, 'sprinter/project_details.html', context)

def add_project(request):
    project_title = request.POST['project_title']
    proj = Project(project_title=project_title)
    proj.save()
    return redirect('sprinter:projects_list')

def delete_project(request, project_id):
    proj = Project.objects.get(id=project_id)
    proj.delete()
    return redirect('sprinter:projects_list')

def add_story(request):
    return HttpResponse("You can add new user's story here.")

def edit_story(request, story_id):
    return HttpResponse("You are editing story number %s now." % story_id)

def edit_project(request, project_title):
    return HttpResponse("You are editing project %s" % project_title)

super_sprinter/sprinter/templates/sprinter/add_project.html
{% extends 'sprinter/base.html' %}

{% block title %}Add a new project!{% endblock %}

{% block content %}



{% endblock %}

super_sprinter/sprinter/templates/sprinter/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
    Super Sprinter 5000 - {% block title %}{% endblock %}
    </title>
</head>
<body>

<div id="content">
    {% block content %}{% endblock %}
</div>

</body>
</html>

super_sprinter/sprinter/templates/sprinter/project_details.html
{% extends "sprinter/base.html" %}

{% block title %}Project details{% endblock %}

{% block content %}

<h2>{{ project.project_title }}</h2>

{% if stories %}
    <table border="1">
        <tr>
            <th>Story title</th>
            <th>User story</th>
            <th>Acceptance Criteria</th>
            <th>Business Value</th>
            <th>Estimation</th>
            <th>Story Value</th>
        </tr>
    {% for story in stories %}
        <tr>
            <td>{{ story.story_title }}</td>
            <td>{{ story.user_story }}</td>
            <td>{{ story.acceptance_criteria }}</td>
            <td>{{ story.business_value }}</td>
            <td>{{ story.estimation }}</td>
            <td>{{ story.value }}</td>
        </tr>

    {% endfor %}

    </table>

{% else %}
    This project has no stories
{% endif %}


{% endblock %}

super_sprinter/sprinter/templates/sprinter/projects_list.html
{% extends "sprinter/base.html" %}
{% block title %} List of all projects {% endblock %}

{% block content %}

<h1>List of all projects:</h1>

{% if projects_list %}
    <ul>
    {% for project in projects_list %}
        <li>
            <a href="{% url 'sprinter:project_detail' project.id %}">
                {{ project.project_title }}
            </a>&nbsp;
            <a href="{% url 'sprinter:delete_project' project.id %}">
                <small>delete</small>
            </a>
        </li>
    {% endfor %}
    </ul>
{% else %}
 <p>No projects are available.</p>
{% endif %}

<br><br>
<hr>


<h2>Add a new project</h2>

{% if error_message %}
    <p><strong>
        {{ error_message }}
    </strong></p>
{% endif %}

<form action="{% url 'sprinter:add_project' %}" method="post">
    {% csrf_token %}
    <label for="project_title">Project title:</label>
    <input type="text" name="project_title" id="project_title">
    <input type="submit" value="Send">
</form>

{% endblock %}